// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: state_channel.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateStateField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field string `protobuf:"bytes,1,opt,name=Field,proto3" json:"Field,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *UpdateStateField) Reset() {
	*x = UpdateStateField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_channel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStateField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStateField) ProtoMessage() {}

func (x *UpdateStateField) ProtoReflect() protoreflect.Message {
	mi := &file_state_channel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStateField.ProtoReflect.Descriptor instead.
func (*UpdateStateField) Descriptor() ([]byte, []int) {
	return file_state_channel_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateStateField) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *UpdateStateField) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type StateChannelCommitData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address      []byte              `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	UpdateFields []*UpdateStateField `protobuf:"bytes,2,rep,name=UpdateFields,proto3" json:"UpdateFields,omitempty"`
}

func (x *StateChannelCommitData) Reset() {
	*x = StateChannelCommitData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_channel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateChannelCommitData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChannelCommitData) ProtoMessage() {}

func (x *StateChannelCommitData) ProtoReflect() protoreflect.Message {
	mi := &file_state_channel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChannelCommitData.ProtoReflect.Descriptor instead.
func (*StateChannelCommitData) Descriptor() ([]byte, []int) {
	return file_state_channel_proto_rawDescGZIP(), []int{1}
}

func (x *StateChannelCommitData) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *StateChannelCommitData) GetUpdateFields() []*UpdateStateField {
	if x != nil {
		return x.UpdateFields
	}
	return nil
}

type CommitAccountStateChannelData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address            []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	CloseSmartContract bool   `protobuf:"varint,2,opt,name=CloseSmartContract,proto3" json:"CloseSmartContract,omitempty"`
	Amount             []byte `protobuf:"bytes,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
}

func (x *CommitAccountStateChannelData) Reset() {
	*x = CommitAccountStateChannelData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_channel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitAccountStateChannelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitAccountStateChannelData) ProtoMessage() {}

func (x *CommitAccountStateChannelData) ProtoReflect() protoreflect.Message {
	mi := &file_state_channel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitAccountStateChannelData.ProtoReflect.Descriptor instead.
func (*CommitAccountStateChannelData) Descriptor() ([]byte, []int) {
	return file_state_channel_proto_rawDescGZIP(), []int{2}
}

func (x *CommitAccountStateChannelData) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *CommitAccountStateChannelData) GetCloseSmartContract() bool {
	if x != nil {
		return x.CloseSmartContract
	}
	return false
}

func (x *CommitAccountStateChannelData) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

type StateChannelCommitSign struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Sign      []byte `protobuf:"bytes,2,opt,name=Sign,proto3" json:"Sign,omitempty"`
}

func (x *StateChannelCommitSign) Reset() {
	*x = StateChannelCommitSign{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_channel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateChannelCommitSign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChannelCommitSign) ProtoMessage() {}

func (x *StateChannelCommitSign) ProtoReflect() protoreflect.Message {
	mi := &file_state_channel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChannelCommitSign.ProtoReflect.Descriptor instead.
func (*StateChannelCommitSign) Descriptor() ([]byte, []int) {
	return file_state_channel_proto_rawDescGZIP(), []int{3}
}

func (x *StateChannelCommitSign) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *StateChannelCommitSign) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

type StateChannelCommitDatas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signs    []*StateChannelCommitSign `protobuf:"bytes,1,rep,name=Signs,proto3" json:"Signs,omitempty"`
	Datas    []*StateChannelCommitData `protobuf:"bytes,2,rep,name=Datas,proto3" json:"Datas,omitempty"`
	Receipts []*Receipt                `protobuf:"bytes,3,rep,name=Receipts,proto3" json:"Receipts,omitempty"`
}

func (x *StateChannelCommitDatas) Reset() {
	*x = StateChannelCommitDatas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_channel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateChannelCommitDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChannelCommitDatas) ProtoMessage() {}

func (x *StateChannelCommitDatas) ProtoReflect() protoreflect.Message {
	mi := &file_state_channel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChannelCommitDatas.ProtoReflect.Descriptor instead.
func (*StateChannelCommitDatas) Descriptor() ([]byte, []int) {
	return file_state_channel_proto_rawDescGZIP(), []int{4}
}

func (x *StateChannelCommitDatas) GetSigns() []*StateChannelCommitSign {
	if x != nil {
		return x.Signs
	}
	return nil
}

func (x *StateChannelCommitDatas) GetDatas() []*StateChannelCommitData {
	if x != nil {
		return x.Datas
	}
	return nil
}

func (x *StateChannelCommitDatas) GetReceipts() []*Receipt {
	if x != nil {
		return x.Receipts
	}
	return nil
}

var File_state_channel_proto protoreflect.FileDescriptor

var file_state_channel_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x1a, 0x0d, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x77, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a,
	0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x43, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x0c,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x81, 0x01, 0x0a,
	0x1d, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18,
	0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2e, 0x0a, 0x12, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x53, 0x6d, 0x61, 0x72, 0x74,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x4a, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x22, 0xc1, 0x01, 0x0a,
	0x17, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x44, 0x61, 0x74, 0x61, 0x73, 0x12, 0x3b, 0x0a, 0x05, 0x53, 0x69, 0x67, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x05,
	0x53, 0x69, 0x67, 0x6e, 0x73, 0x12, 0x3b, 0x0a, 0x05, 0x44, 0x61, 0x74, 0x61, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x44, 0x61, 0x74,
	0x61, 0x73, 0x12, 0x2c, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x2e, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x08, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73,
	0x42, 0x35, 0x0a, 0x2b, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x6e, 0x6f, 0x64,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65,
	0x64, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5a,
	0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_state_channel_proto_rawDescOnce sync.Once
	file_state_channel_proto_rawDescData = file_state_channel_proto_rawDesc
)

func file_state_channel_proto_rawDescGZIP() []byte {
	file_state_channel_proto_rawDescOnce.Do(func() {
		file_state_channel_proto_rawDescData = protoimpl.X.CompressGZIP(file_state_channel_proto_rawDescData)
	})
	return file_state_channel_proto_rawDescData
}

var file_state_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_state_channel_proto_goTypes = []interface{}{
	(*UpdateStateField)(nil),              // 0: state_channel.UpdateStateField
	(*StateChannelCommitData)(nil),        // 1: state_channel.StateChannelCommitData
	(*CommitAccountStateChannelData)(nil), // 2: state_channel.CommitAccountStateChannelData
	(*StateChannelCommitSign)(nil),        // 3: state_channel.StateChannelCommitSign
	(*StateChannelCommitDatas)(nil),       // 4: state_channel.StateChannelCommitDatas
	(*Receipt)(nil),                       // 5: receipt.Receipt
}
var file_state_channel_proto_depIdxs = []int32{
	0, // 0: state_channel.StateChannelCommitData.UpdateFields:type_name -> state_channel.UpdateStateField
	3, // 1: state_channel.StateChannelCommitDatas.Signs:type_name -> state_channel.StateChannelCommitSign
	1, // 2: state_channel.StateChannelCommitDatas.Datas:type_name -> state_channel.StateChannelCommitData
	5, // 3: state_channel.StateChannelCommitDatas.Receipts:type_name -> receipt.Receipt
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_state_channel_proto_init() }
func file_state_channel_proto_init() {
	if File_state_channel_proto != nil {
		return
	}
	file_receipt_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_state_channel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStateField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_channel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateChannelCommitData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_channel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitAccountStateChannelData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_channel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateChannelCommitSign); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_channel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateChannelCommitDatas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_state_channel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_channel_proto_goTypes,
		DependencyIndexes: file_state_channel_proto_depIdxs,
		MessageInfos:      file_state_channel_proto_msgTypes,
	}.Build()
	File_state_channel_proto = out.File
	file_state_channel_proto_rawDesc = nil
	file_state_channel_proto_goTypes = nil
	file_state_channel_proto_depIdxs = nil
}
